import { ServiceOrder, Equipment, EquipmentTypeConfig, User, SectorConfig, AppNotification } from '../types';

export const INITIAL_EQUIPMENT_TYPES: EquipmentTypeConfig[] = [
  { id: 'desktop', name: 'Desktop / Computador', iconName: 'Cpu', description: 'Gabinete/Torre de computador de mesa', isSystem: true },
  { id: 'notebook', name: 'Notebook / Laptop', iconName: 'Laptop', description: 'Computador portátil institucional', isSystem: true },
  { id: 'impressora', name: 'Impressora / Multifuncional', iconName: 'Printer', description: 'Impressora laser, jato de tinta ou térmica', isSystem: true },
  { id: 'nobreak', name: 'Nobreak / Estabilizador', iconName: 'Zap', description: 'Proteção elétrica e bateria de backup', isSystem: true },
  { id: 'monitor', name: 'Monitor de Vídeo', iconName: 'Monitor', description: 'Tela LED/LCD individual', isSystem: true },
  { id: 'switch', name: 'Switch de Rede', iconName: 'Radio', description: 'Distribuidor de rede cabeada Ethernet', isSystem: true },
  { id: 'roteador', name: 'Roteador / Wi-Fi', iconName: 'Radio', description: 'Ponto de acesso e roteamento sem fio', isSystem: true },
  { id: 'scanner', name: 'Scanner de Mesa', iconName: 'Printer', description: 'Digitalizador de processos e documentos', isSystem: false },
  { id: 'servidor', name: 'Servidor / Storage', iconName: 'Server', description: 'Servidor de banco de dados ou arquivos', isSystem: false },
  { id: 'outro', name: 'Outro Periférico', iconName: 'HardDrive', description: 'Projetor, periférico ou equipamento diverso', isSystem: true },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Carlos Eduardo Santos',
    email: 'carlos.santos@teresina.pi.gov.br',
    role: 'admin',
    sector: 'Setor de TI / CPD',
    registration: '84910-2',
    phone: '(86) 3215-7510',
    specialty: 'Coordenação Geral & Infraestrutura',
    status: 'ativo',
    joinedDate: '2019-02-10',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-2',
    name: 'Marcos Vinícius Melo',
    email: 'marcos.melo@teresina.pi.gov.br',
    role: 'tecnico',
    sector: 'Setor de TI / CPD',
    registration: '92104-5',
    phone: '(86) 3215-7512',
    specialty: 'Manutenção de Hardware & Desktops',
    status: 'ativo',
    joinedDate: '2021-06-15',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-3',
    name: 'Ana Clara Rocha',
    email: 'ana.rocha@teresina.pi.gov.br',
    role: 'tecnico',
    sector: 'Setor de TI / CPD',
    registration: '93452-1',
    phone: '(86) 3215-7513',
    specialty: 'Redes de Computadores & Nobreaks',
    status: 'ativo',
    joinedDate: '2022-01-20',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-4',
    name: 'Lucas Barbosa Lima',
    email: 'lucas.barbosa@teresina.pi.gov.br',
    role: 'tecnico',
    sector: 'Setor de TI / CPD',
    registration: '95112-8',
    phone: '(86) 3215-7514',
    specialty: 'Impressoras, Periféricos & Sistemas',
    status: 'ativo',
    joinedDate: '2023-04-03',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-5',
    name: 'Dra. Renata Meireles',
    email: 'renata.meireles@teresina.pi.gov.br',
    role: 'solicitante',
    sector: 'Gabinete do Superintendente',
    registration: '77219-0',
    phone: '(86) 3215-7501',
    status: 'ativo',
    joinedDate: '2018-03-01',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-6',
    name: 'Eng. Roberto Alencar',
    email: 'roberto.alencar@teresina.pi.gov.br',
    role: 'solicitante',
    sector: 'Gerência de Obras e Serviços Públicos (GOSP)',
    registration: '68114-3',
    phone: '(86) 3215-7530',
    status: 'ativo',
    joinedDate: '2016-08-12',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_SECTORS: SectorConfig[] = [
  { 
    id: 'sec-1', 
    name: 'Gerência de Obras e Serviços Públicos', 
    abbreviation: 'GOSP', 
    headName: 'Eng. Roberto Alencar', 
    phone: '(86) 3215-7530',
    email: 'gosp.sdul@teresina.pi.gov.br',
    location: 'Bloco A - Térreo, Sala 102',
    description: 'Responsável pela execução e fiscalização de obras viárias, drenagem e serviços públicos urbanos da Zona Leste.'
  },
  { 
    id: 'sec-2', 
    name: 'Gerência de Habitação e Regularização Fundiária', 
    abbreviation: 'GHRF', 
    headName: 'Mariana Fontenele', 
    phone: '(86) 3215-7540',
    email: 'habitacao.sdul@teresina.pi.gov.br',
    location: 'Bloco B - 1º Andar, Sala 204',
    description: 'Atendimento a programas habitacionais, titulação de imóveis e regularização urbana.'
  },
  { 
    id: 'sec-3', 
    name: 'Gerência de Fiscalização e Posturas', 
    abbreviation: 'GFP', 
    headName: 'Cap. Valdir Soares', 
    phone: '(86) 3215-7550',
    email: 'fiscalizacao.sdul@teresina.pi.gov.br',
    location: 'Bloco A - Térreo, Sala 106',
    description: 'Fiscalização de obras particulares, ocupação do solo, calçadas e cumprimento do código de posturas.'
  },
  { 
    id: 'sec-4', 
    name: 'Gerência de Meio Ambiente', 
    abbreviation: 'GMA', 
    headName: 'Beatriz Vasconcelos', 
    phone: '(86) 3215-7560',
    email: 'meioambiente.sdul@teresina.pi.gov.br',
    location: 'Bloco B - 1º Andar, Sala 208',
    description: 'Autorizações de poda, fiscalização ambiental, arborização e preservação de áreas verdes da Zona Leste.'
  },
  { 
    id: 'sec-5', 
    name: 'Gerência Financeira e Contábil', 
    abbreviation: 'GFC', 
    headName: 'Francisco Chagas', 
    phone: '(86) 3215-7520',
    email: 'financeiro.sdul@teresina.pi.gov.br',
    location: 'Bloco C - 2º Andar, Sala 301',
    description: 'Gestão orçamentária, empenhos, liquidação de despesas e prestação de contas da SDU Leste.'
  },
  { 
    id: 'sec-6', 
    name: 'Gerência de Protocolo e Atendimento', 
    abbreviation: 'GPA', 
    headName: 'Socorro Mendes', 
    phone: '(86) 3215-7505',
    email: 'protocolo.sdul@teresina.pi.gov.br',
    location: 'Hall de Entrada Principal - Térreo',
    description: 'Recepção e triagem de cidadãos, abertura de processos administrativos e distribuição de requerimentos.'
  },
  { 
    id: 'sec-7', 
    name: 'Gabinete do Superintendente', 
    abbreviation: 'GAB', 
    headName: 'Superintendência SDU Leste', 
    phone: '(86) 3215-7501',
    email: 'gabinete.sdul@teresina.pi.gov.br',
    location: 'Bloco C - 2º Andar, Gabinete Central',
    description: 'Direção geral, despacho de decisões colegiadas e representação institucional da Superintendência.'
  },
  { 
    id: 'sec-8', 
    name: 'Setor de TI / CPD', 
    abbreviation: 'CPD', 
    headName: 'Carlos Eduardo Santos', 
    phone: '(86) 3215-7510',
    email: 'ti.sduleste@teresina.pi.gov.br',
    location: 'Bloco C - Subsolo Técnico / CPD',
    description: 'Suporte tecnológico, infraestrutura de redes, manutenção preventiva e corretiva de computadores e impressoras.'
  },
];

export const INITIAL_EQUIPMENTS: Equipment[] = [
  {
    id: 'eq-1',
    type: 'desktop',
    brand: 'Dell',
    model: 'OptiPlex 3080 SFF (Core i5 10ª Gen, 16GB)',
    assetNumber: 'PMT-SDUL-04821',
    serialNumber: 'BR54921X',
    sector: 'Gerência de Obras e Serviços Públicos (GOSP)',
    locationDetails: 'Mesa 04 - Sala dos Engenheiros',
    status: 'em_manutencao',
    purchaseYear: 2021,
    lastMaintenanceDate: '2026-03-10T10:00:00Z',
    notes: 'Apresenta tela azul ao abrir software AutoCAD',
  },
  {
    id: 'eq-2',
    type: 'impressora',
    brand: 'Brother',
    model: 'DCP-L2540DW Multifuncional Laser',
    assetNumber: 'PMT-SDUL-03190',
    serialNumber: 'U63981G8N4129',
    sector: 'Gerência de Protocolo e Atendimento',
    locationDetails: 'Balcão de Recepção e Entrada',
    status: 'operacional',
    purchaseYear: 2020,
    lastMaintenanceDate: '2026-03-12T14:30:00Z',
    notes: 'Troca periódica de rolete tracionador realizada',
  },
  {
    id: 'eq-3',
    type: 'nobreak',
    brand: 'SMS',
    model: 'Manager III Senoidal 1400VA',
    assetNumber: 'PMT-SDUL-05118',
    serialNumber: 'SMS9920141',
    sector: 'Setor de TI / CPD',
    locationDetails: 'Rack do Servidor de Arquivos SDU Leste',
    status: 'em_manutencao',
    purchaseYear: 2022,
    lastMaintenanceDate: '2026-03-14T09:00:00Z',
    notes: 'Baterias internas esgotadas, apito sonoro contínuo',
  },
  {
    id: 'eq-4',
    type: 'notebook',
    brand: 'Lenovo',
    model: 'ThinkPad E14 Gen 4',
    assetNumber: 'PMT-SDUL-06042',
    serialNumber: 'PF3N81L2',
    sector: 'Gabinete do Superintendente',
    locationDetails: 'Gabinete Principal',
    status: 'em_manutencao',
    purchaseYear: 2023,
    lastMaintenanceDate: '2026-03-13T16:00:00Z',
    notes: 'Tela piscando ao movimentar a dobradiça (cabo flat)',
  },
  {
    id: 'eq-5',
    type: 'desktop',
    brand: 'HP',
    model: 'ProDesk 400 G6',
    assetNumber: 'PMT-SDUL-04210',
    serialNumber: 'MXL0192931',
    sector: 'Gerência Financeira e Contábil',
    locationDetails: 'Mesa da Tesouraria',
    status: 'operacional',
    purchaseYear: 2021,
    lastMaintenanceDate: '2026-03-08T11:00:00Z',
    notes: 'Configurado com certificado digital A3 em token SafeNet',
  },
  {
    id: 'eq-6',
    type: 'switch',
    brand: 'Cisco',
    model: 'Catalyst 2960-X 24 Portas Gigabit',
    assetNumber: 'PMT-SDUL-02091',
    serialNumber: 'FCW2104B09',
    sector: 'Setor de TI / CPD',
    locationDetails: 'Armário de Telecomunicações - Piso 1',
    status: 'operacional',
    purchaseYear: 2019,
    lastMaintenanceDate: '2026-02-15T08:00:00Z',
  },
];

export const INITIAL_ORDERS: ServiceOrder[] = [
  {
    id: 'OS-2026-0001',
    createdAt: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    slaHours: 24,
    slaDeadline: new Date(Date.now() - 12 * 3600 * 1000).toISOString(), // Estourada para demonstração de SLA
    status: 'em_andamento',
    priority: 'media',
    category: 'hardware',
    requester: {
      name: 'Eng. Roberto Alencar',
      email: 'roberto.alencar@teresina.pi.gov.br',
      phone: '(86) 3215-7530',
      sector: 'Gerência de Obras e Serviços Públicos (GOSP)',
      registration: '68114-3',
    },
    technician: {
      id: 'usr-2',
      name: 'Marcos Vinícius Melo',
      email: 'marcos.melo@teresina.pi.gov.br',
      phone: '(86) 3215-7512',
    },
    equipment: {
      type: 'desktop',
      brand: 'Dell',
      model: 'OptiPlex 3080 SFF',
      assetNumber: 'PMT-SDUL-04821',
      serialNumber: 'BR54921X',
      accessories: ['Cabo de Força Original', 'Adaptador DisplayPort para VGA'],
    },
    issueDescription: 'Máquina travando constantemente ao executar projetos do AutoCAD da pavimentação asfáltica. Em seguida desliga e apresenta mensagem de erro de leitura de disco S.M.A.R.T.',
    technicalDiagnosis: 'Disco HD mecânico original de 1TB com setores defeituosos (bad blocks) e lentidão extrema de I/O. Necessária migração para SSD NVMe 500GB e limpeza do cooler da CPU.',
    actionsTaken: [
      'Executado diagnóstico de hardware via Dell ePSA (Código de erro 2000-0142)',
      'Backup de segurança da pasta C:\\Obras_2026 realizado em unidade externa do CPD',
      'Instalado SSD Kingston NVMe 500GB novo do estoque de peças',
      'Clonagem do sistema operacional Windows 11 Pro PMT e instalação dos drivers oficiais',
    ],
    materialsUsed: [
      {
        id: 'mat-1',
        name: 'SSD M.2 NVMe 500GB Kingston NV2',
        quantity: 1,
        unit: 'un',
        partNumber: 'SNV2S/500G',
        dateAdded: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
      },
      {
        id: 'mat-2',
        name: 'Pasta Térmica Prata Arctic Silver 5 (1g)',
        quantity: 1,
        unit: 'aplica',
        dateAdded: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
      },
    ],
    checklist: {
      startupTest: true,
      networkTest: true,
      peripheralTest: true,
      internalCleaning: true,
      stressPrintTest: false,
      notes: 'Falta apenas finalizar os testes de estresse com o AutoCAD antes de liberar para o setor.',
    },
    timeline: [
      {
        id: 't-1',
        timestamp: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
        authorName: 'Eng. Roberto Alencar',
        authorRole: 'Solicitante',
        action: 'Abertura da Ordem de Serviço',
        notes: 'Chamado cadastrado via formulário do portal CPD.',
        newStatus: 'aberta',
      },
      {
        id: 't-2',
        timestamp: new Date(Date.now() - 32 * 3600 * 1000).toISOString(),
        authorName: 'Carlos Eduardo Santos',
        authorRole: 'Chefe do CPD',
        action: 'Triagem e Atribuição',
        notes: 'Equipamento recebido no balcão do CPD e encaminhado à bancada 2.',
        oldStatus: 'aberta',
        newStatus: 'atribuida',
      },
      {
        id: 't-3',
        timestamp: new Date(Date.now() - 28 * 3600 * 1000).toISOString(),
        authorName: 'Marcos Vinícius Melo',
        authorRole: 'Técnico Responsável',
        action: 'Início do Diagnóstico e Manutenção',
        notes: 'Bancada iniciada. Constatada falha no HD.',
        oldStatus: 'atribuida',
        newStatus: 'em_andamento',
      },
    ],
  },
  {
    id: 'OS-2026-0002',
    createdAt: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    slaHours: 8,
    slaDeadline: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    status: 'resolvida',
    priority: 'alta',
    category: 'impressora',
    requester: {
      name: 'Socorro Mendes',
      email: 'socorro.mendes@teresina.pi.gov.br',
      phone: '(86) 3215-7505',
      sector: 'Gerência de Protocolo e Atendimento',
      registration: '54210-9',
    },
    technician: {
      id: 'usr-3',
      name: 'Ana Clara Rocha',
      email: 'ana.rocha@teresina.pi.gov.br',
      phone: '(86) 3215-7513',
    },
    equipment: {
      type: 'impressora',
      brand: 'Brother',
      model: 'DCP-L2540DW Multifuncional',
      assetNumber: 'PMT-SDUL-03190',
      serialNumber: 'U63981G8N4129',
      accessories: ['Cabo USB', 'Cabo de Energia'],
    },
    issueDescription: 'Impressora atolando folhas no tracionador de entrada e manchando a lateral direita dos comprovantes de protocolo com listras pretas.',
    technicalDiagnosis: 'Rolete pick-up roller ressecado e acúmulo de pó de toner residual no rolo fusor térmico.',
    actionsTaken: [
      'Desmontagem parcial do conjunto de tracionamento de papel',
      'Limpeza profunda do caminho do papel e lubrificação com álcool isopropílico',
      'Substituição do rolete de tração (Pick-up roller)',
      'Impressão contínua de 50 páginas de teste com êxito total',
    ],
    materialsUsed: [
      {
        id: 'mat-3',
        name: 'Rolete Tracionador Pick-Up Roller Brother',
        quantity: 1,
        unit: 'un',
        dateAdded: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
      },
    ],
    checklist: {
      startupTest: true,
      networkTest: true,
      peripheralTest: true,
      internalCleaning: true,
      stressPrintTest: true,
      notes: 'Equipamento testado e pronto para devolução com recibo de entrega.',
    },
    timeline: [
      {
        id: 't-4',
        timestamp: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
        authorName: 'Socorro Mendes',
        authorRole: 'Solicitante',
        action: 'Abertura da OS',
        notes: 'Prioridade alta devido ao atendimento ao cidadão no protocolo.',
        newStatus: 'aberta',
      },
      {
        id: 't-5',
        timestamp: new Date(Date.now() - 15 * 3600 * 1000).toISOString(),
        authorName: 'Ana Clara Rocha',
        authorRole: 'Técnica Responsável',
        action: 'Atendimento Realizado e Concluído',
        notes: 'Impressora limpa e revisada.',
        oldStatus: 'em_andamento',
        newStatus: 'resolvida',
      },
    ],
  },
  {
    id: 'OS-2026-0003',
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    slaHours: 4,
    slaDeadline: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    status: 'atribuida',
    priority: 'urgente',
    category: 'rede',
    requester: {
      name: 'Cap. Valdir Soares',
      email: 'valdir.soares@teresina.pi.gov.br',
      phone: '(86) 3215-7550',
      sector: 'Gerência de Fiscalização e Posturas (GFP)',
      registration: '88102-1',
    },
    technician: {
      id: 'usr-4',
      name: 'Lucas Barbosa Lima',
      email: 'lucas.barbosa@teresina.pi.gov.br',
      phone: '(86) 3215-7514',
    },
    equipment: {
      type: 'switch',
      brand: 'TP-Link',
      model: 'TL-SG1016D 16 Portas',
      assetNumber: 'PMT-SDUL-01980',
      serialNumber: '22019481902',
      accessories: ['Fonte de Alimentação'],
    },
    issueDescription: 'Toda a sala de fiscalização ficou sem acesso ao sistema e-Teresina e internet às 08h. As luzes das portas 5 a 12 estão apagadas no rack.',
    technicalDiagnosis: 'Em análise no local.',
    actionsTaken: ['Técnico deslocado para o rack da fiscalização com testador de cabo de rede Fluke.'],
    materialsUsed: [],
    checklist: {
      startupTest: false,
      networkTest: false,
      peripheralTest: false,
      internalCleaning: false,
      stressPrintTest: false,
    },
    timeline: [
      {
        id: 't-6',
        timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
        authorName: 'Cap. Valdir Soares',
        authorRole: 'Solicitante',
        action: 'Abertura de Chamado Urgente',
        notes: 'Fiscalização parada sem emitir autos e notificações.',
        newStatus: 'aberta',
      },
      {
        id: 't-7',
        timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
        authorName: 'Carlos Eduardo Santos',
        authorRole: 'Chefe do CPD',
        action: 'Designado Técnico de Infraestrutura',
        notes: 'Lucas Lima designado para atendimento presencial imediato.',
        oldStatus: 'aberta',
        newStatus: 'atribuida',
      },
    ],
  },
  {
    id: 'OS-2026-0004',
    createdAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
    slaHours: 24,
    slaDeadline: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 50 * 3600 * 1000).toISOString(),
    closedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    status: 'fechada',
    priority: 'media',
    category: 'software',
    requester: {
      name: 'Francisco Chagas',
      email: 'francisco.chagas@teresina.pi.gov.br',
      phone: '(86) 3215-7520',
      sector: 'Gerência Financeira e Contábil',
      registration: '51902-8',
    },
    technician: {
      id: 'usr-3',
      name: 'Ana Clara Rocha',
      email: 'ana.rocha@teresina.pi.gov.br',
    },
    equipment: {
      type: 'desktop',
      brand: 'HP',
      model: 'ProDesk 400 G6',
      assetNumber: 'PMT-SDUL-04210',
      serialNumber: 'MXL0192931',
      accessories: [],
    },
    issueDescription: 'Instalação da nova versão do sistema de empenho e liquidação da Secretaria de Finanças e configuração do Token A3 Certisign.',
    technicalDiagnosis: 'Instalado Java Runtime 8u381 32/64 bits, SafeNet Authentication Client e navegador homologado.',
    actionsTaken: [
      'Desinstalada versão antiga e conflitante do driver do token',
      'Configuradas exceções de segurança no navegador Edge',
      'Teste de assinatura de documento digital efetuado com sucesso',
    ],
    materialsUsed: [],
    checklist: {
      startupTest: true,
      networkTest: true,
      peripheralTest: true,
      internalCleaning: false,
      stressPrintTest: false,
    },
    delivery: {
      receivedBy: 'Francisco Chagas',
      receiverRegistration: '51902-8',
      receiverCpf: '123.456.789-00',
      receiverSector: 'Gerência Financeira e Contábil',
      date: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
      confirmationNotes: 'Atendimento realizado in loco com plena funcionalidade do certificado.',
    },
    rating: {
      stars: 5,
      comment: 'Atendimento nota 10 da equipe da SDU Leste! Rápido e muito prestativo.',
      date: new Date(Date.now() - 47 * 3600 * 1000).toISOString(),
      ratedBy: 'Francisco Chagas',
    },
    timeline: [
      {
        id: 't-8',
        timestamp: new Date(Date.now() - 72 * 3600 * 1000).toISOString(),
        authorName: 'Francisco Chagas',
        authorRole: 'Solicitante',
        action: 'Abertura da OS',
        newStatus: 'aberta',
      },
      {
        id: 't-9',
        timestamp: new Date(Date.now() - 50 * 3600 * 1000).toISOString(),
        authorName: 'Ana Clara Rocha',
        authorRole: 'Técnica',
        action: 'Serviço Finalizado',
        oldStatus: 'em_andamento',
        newStatus: 'resolvida',
      },
      {
        id: 't-10',
        timestamp: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
        authorName: 'Francisco Chagas',
        authorRole: 'Solicitante',
        action: 'Entrega e Recebimento Homologado',
        oldStatus: 'resolvida',
        newStatus: 'fechada',
      },
    ],
  },
  {
    id: 'OS-2026-0005',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    slaHours: 24,
    slaDeadline: new Date(Date.now() + 22 * 3600 * 1000).toISOString(),
    status: 'triagem',
    priority: 'media',
    category: 'apoio',
    requester: {
      name: 'Mariana Fontenele',
      email: 'mariana.fontenele@teresina.pi.gov.br',
      phone: '(86) 3215-7540',
      sector: 'Gerência de Habitação e Regularização Fundiária',
      registration: '69420-1',
    },
    equipment: {
      type: 'notebook',
      brand: 'Dell',
      model: 'Vostro 3400',
      assetNumber: 'PMT-SDUL-05890',
      serialNumber: '9M48102',
      accessories: ['Carregador Original'],
    },
    issueDescription: 'Necessidade de configuração de acesso remoto VPN da Prefeitura para plantão do final de semana e suporte na importação da planilha de cadastros do Minha Casa Minha Vida.',
    actionsTaken: [],
    materialsUsed: [],
    checklist: {
      startupTest: false,
      networkTest: false,
      peripheralTest: false,
      internalCleaning: false,
      stressPrintTest: false,
    },
    timeline: [
      {
        id: 't-11',
        timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        authorName: 'Mariana Fontenele',
        authorRole: 'Solicitante',
        action: 'Abertura da OS',
        notes: 'Aguardando parecer do CPD para liberar chave VPN.',
        newStatus: 'aberta',
      },
      {
        id: 't-12',
        timestamp: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
        authorName: 'Carlos Eduardo Santos',
        authorRole: 'Chefe do CPD',
        action: 'Em Triagem de Segurança',
        notes: 'Verificando autorização formal da superintendência.',
        oldStatus: 'aberta',
        newStatus: 'triagem',
      },
    ],
  },
  {
    id: 'OS-2026-0006',
    createdAt: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    slaHours: 48,
    slaDeadline: new Date(Date.now() + 22 * 3600 * 1000).toISOString(),
    status: 'aguardando_peca',
    priority: 'baixa',
    category: 'hardware',
    requester: {
      name: 'Dra. Renata Meireles',
      email: 'renata.meireles@teresina.pi.gov.br',
      phone: '(86) 3215-7501',
      sector: 'Gabinete do Superintendente',
      registration: '77219-0',
    },
    technician: {
      id: 'usr-2',
      name: 'Marcos Vinícius Melo',
      email: 'marcos.melo@teresina.pi.gov.br',
    },
    equipment: {
      type: 'notebook',
      brand: 'Lenovo',
      model: 'ThinkPad E14 Gen 4',
      assetNumber: 'PMT-SDUL-06042',
      serialNumber: 'PF3N81L2',
      accessories: ['Fonte USB-C', 'Bolsa de Transporte'],
    },
    issueDescription: 'Tela apaga quando abre a tampa em mais de 90 graus. Apresenta artefatos visuais.',
    technicalDiagnosis: 'Cabo flat EDP do display LCD rompido por desgaste da dobradiça esquerda.',
    actionsTaken: [
      'Desmontagem da carcaça frontal e teste do conector de 30 pinos',
      'Solicitado cabo flat novo ao almoxarifado central da Prefeitura de Teresina (Processo Adm nº 042/2026)',
    ],
    materialsUsed: [],
    checklist: {
      startupTest: true,
      networkTest: false,
      peripheralTest: false,
      internalCleaning: true,
      stressPrintTest: false,
      notes: 'Equipamento guardado em armário seguro do CPD aguardando chegada do cabo de reposição.',
    },
    timeline: [
      {
        id: 't-13',
        timestamp: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
        authorName: 'Dra. Renata Meireles',
        authorRole: 'Solicitante',
        action: 'Abertura da OS',
        newStatus: 'aberta',
      },
      {
        id: 't-14',
        timestamp: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
        authorName: 'Marcos Vinícius Melo',
        authorRole: 'Técnico',
        action: 'Status alterado para Aguardando Peça',
        notes: 'Pedido de compra/fornecimento emitido para a Secretaria de Administração.',
        oldStatus: 'em_andamento',
        newStatus: 'aguardando_peca',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'SLA Próximo do Limite',
    message: 'A Ordem de Serviço OS-2026-0003 (Urgente - Rede Fiscalização) tem menos de 2 horas para expirar.',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    read: false,
    orderId: 'OS-2026-0003',
    type: 'warning',
  },
  {
    id: 'notif-2',
    title: 'Nova Ordem de Serviço Aberta',
    message: 'OS-2026-0005 aberta pela Gerência de Habitação. Aguardando triagem.',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    read: false,
    orderId: 'OS-2026-0005',
    type: 'info',
  },
  {
    id: 'notif-3',
    title: 'OS Pronta para Entrega',
    message: 'OS-2026-0002 (Impressora Protocolo) foi finalizada e está disponível para retirada no balcão do CPD.',
    timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    read: true,
    orderId: 'OS-2026-0002',
    type: 'success',
  },
];
